### ISSUE TITLE
Full cloud.ply

### ISSUE THREAD

**Issue by DieProgrammIDE** [centreborelli/s2p#108]
Hello,
How can i get a Point Cloud from the whole Area?

**Comment by gfacciol** [comment]
Yes, you can joint all the ply in a single point cloud. 
However, the ply format is not adapted to handle billions of points, so instead we use a potree. 
The script utils/s2p_to_potree.py should do the job:

https://github.com/centreborelli/s2p/blob/7121ee3f299e163e76f6c92c8c8fc163b02835f2/utils/s2p_to_potree.py#L176

**Comment by DieProgrammIDE** [comment]
I need it in the LAS Format to process with danesfield.
That's why i want to merge them.

**Comment by gfacciol** [comment]
I'm not aware of a single tool that would do the conversion, but I think it should be easy to script as: 

1st: convert all ply to las using  plyfile and laspy to read and write each file 
    https://github.com/dranjan/python-plyfile
    https://github.com/laspy/laspy
    
2nd: merge all the las files using lasmerge
    https://rapidlasso.com/lastools/lasmerge/
