### ISSUE TITLE
if exogenous_dem_geoid_mode is True or False 

### ISSUE THREAD

**Issue by lionlai1989** [centreborelli/s2p#109]
In [`s2p/rpc_utils.py`](https://github.com/centreborelli/s2p/blob/7121ee3f299e163e76f6c92c8c8fc163b02835f2/s2p/rpc_utils.py#L306), it states
```python
    if exogenous_dem_geoid_mode is True:
        z = geographiclib.geoid_to_ellipsoid(lat, lon, z)
```
When `exogenous_dem_geoid_mode` is `True`, then converting height from geoid to ellipsoid.  
My questions are:  
1, Why is it not `if exogenous_dem_geoid_mode is False:`? It makes more sense to me that when `exogenous_dem_geoid_mode` is `False`, then the DEM should be ellipsoid height.
2. Does function `geoid_to_ellipsoid` convert a orthometric height to ellipsoid height? From _**H**_ to _**h**_ as in [geoid height calculator](https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html) states. 
It would be great that if you can clarify these things. Thank you.

**Comment by oleg-alexandrov** [comment]
I think when when exogenous_dem_geoid_mode is true, your input DEM is assumed to be in orthometric (geoid) heights, and then it needs conversion to ellipsoid heights, which is what happens in that code. So, the logic is correct. Ellipsoid heights are lot more convenient to use than orthometric heights for later processing.
