### ISSUE TITLE
Update to latest mgm

### ISSUE THREAD

**Issue by oleg-alexandrov** [centreborelli/s2p#112]
Since mgm is the workhorse of s2p, as far as I know, it may be of interest that mgm can crash on the Mac because of the --fast-math compile switch, which cuts corners when dealing with NaN. I submitted a fix for that, and for another lesser issue (https://github.com/gfacciol/mgm/pull/15#pullrequestreview-900982077).

It may be good if s2p is updated to the latest mgm.

**Comment by carlodef** [comment]
Indeed you are right, thank you @oleg-alexandrov! This is adressed in 8fbe233.
