### ISSUE TITLE
Texturing the 3D Model

### ISSUE THREAD

**Issue by DieProgrammIDE** [centreborelli/s2p#114]
Hello,
Which program could i use to texture my outputted Pointcloud using my Coloured TIFs?
Normally I would have used something like MVS_texturing but I am not able to create the camera parameters for that
I have used the panchromatic Images for creating the Pointcloud and my Goal is a 3D Model of a City.

Thank you!

**Comment by carlodef** [comment]
Hi @DieProgrammIDE, you can add your coloured TIFs in the input json configuration file in order to get a coloured point cloud, by adding a `clr` key next to the `img` key in the input images dict. The coloured TIFs must have the same width and height as the panchromatic images.

**Comment by DieProgrammIDE** [comment]
So one for each panchromatic image?
One of my RGB Images is overexposed in some Areas and can't be corrected. Can I leave it out or do I need to have the "clr" key for every Image?

Also, I assume I need to Pansharpen the Pléiades Neo RGB Images so they have the same width/height, right?

I have attached screenshots with the files.
![Screenshot 2022-03-17 223031](https://user-images.githubusercontent.com/39222199/158898875-a49eb93f-a932-4187-9711-d88c8137d787.png)
![Screenshot 2022-03-17 223113](https://user-images.githubusercontent.com/39222199/158898980-0beccbde-4501-4336-a7fc-983611e727c3.png)


This is the Dataset I use: https://www.intelligence-airbusds.com/imagery/sample-imagery/pleiades-neo-tristereo-marseille/

When I am finished with my 3D Model I would write detailed documentation about how I utilized s2p and various other tools. Maybe you would have interest in linking it. It would include configuration files and the 30cm Data is freely available.

**Comment by carlodef** [comment]
Hi @DieProgrammIDE, only the color image corresponding to the first input image is needed (i.e. only the first element in the `images` sequence in the config dict needs to have a `clr` key).

And yes indeed, you need to pansharpen the color image so that it has the same width and height as the panchromatic image.
