### ISSUE TITLE
Update pyproj>=3.0.0

### ISSUE THREAD

**Issue by lionlai1989** [centreborelli/s2p#124]
The current `pyproj` version in s2p is under `3.0.0`. Could we please update `pyproj` to a more recent version? 

`pyproj==2.6` has been outdated for two years, and many bugs and features have been [solved and added](https://pyproj4.github.io/pyproj/stable/history.html) in `pyproj==3.3.1`.

Thank you.

**Comment by kidanger** [comment]
Fixed in 7acdf7e79eb2f0fdde53a1150da36f27a8fb019e. For the CI, fd9a34f87f72c8a13b75274c9829e0608212c24d was needed as well.
