### ISSUE TITLE
'make test' got an error

### ISSUE THREAD

**Issue by limiao766** [centreborelli/s2p#144]
FAILED tests/end2end_test.py::test_mosaic - FileNotFoundError: [Errno 2] No such file or directory: 'gdal_translate'
FAILED tests/rpc_utils_test.py::test_roi_process[False-/home/lph/s2p/tests/data/expected_output/pair/dsm.tif-True-expected2] - AssertionError: 
============ 2 failed, 31 passed, 5 warnings in 197.86s (0:03:17) =============
make: *** [makefile:19：test] 错误 1

**Comment by carlodef** [comment]
> No such file or directory: 'gdal_translate'

This means that GDAL binaries are not available on your machine. You probably need to install them with something like

```
apt install gdal-bin
```
