### ISSUE TITLE
Make test errors!

### ISSUE THREAD

**Issue by thedodo** [centreborelli/s2p#152]
Hi.
I am having  3 errors when compiling `make test`.
Thanks in advance for the help:

`FAILED tests/end2end_test.py::test_end2end_triplet - AssertionError: 
FAILED tests/end2end_test.py::test_mosaic - AssertionError: assert 0.054745756 <= 0.05
FAILED tests/rpc_utils_test.py::test_roi_process[False-/home/dominik/s2pNew/s2p/tests/data/expected_output/pair/dsm.tif-True-expected2] - AssertionErr...`

Here is the full output of the terminal: 
[make_test.txt](https://github.com/centreborelli/s2p/files/13754711/make_test.txt)

**Comment by ouyuanzheng** [comment]
I've also come across it before. You didn't install it successfully，I installed s2p and used python=3.6.9,  gdal=3.4.2 version

**Comment by thedodo** [comment]
Yes, thank you for your answer. I can confirm that it works with python 3.6. 
On my system python 3.10 was installed and it seems there was some conflicts with this. 
Downgrading my python version to 3.6 and then installing all the dependencies according to this version did fix this issues!
