### ISSUE TITLE
Error: mprod not finite

### ISSUE THREAD

**Issue by lionlai1989** [centreborelli/s2p#47]
I run my Pleiades stereo images with s2p but encountered the following error.
`FAIL("/usr/bin/python3 /home/ubuntu/.local/bin/s2p tmp.json"): mprod A not finite 1 1`
`FAIL("/usr/bin/python3 /home/ubuntu/.local/bin/s2p tmp.json"): mprod B not finite 2 2`

I reckon this error is probably the same as [this](https://github.com/MISS3D/s2p/issues/222).
```			
if (!isfinite(a[i][k]))  
	fail("mprod A not finite %d %d", i, k);  
if (!isfinite(b[k][j]))
	fail("mprod B not finite %d %d", k, j);
```
I actually kind of worked around this error by doing the following.
```
if (!isfinite(a[i][k]))
        a[i][k] = 0;
        //fail("mprod A not finite %d %d", i, k);
if (!isfinite(b[k][j]))
        b[k][j] = 0;
        //fail("mprod B not finite %d %d", k, j);
```

And the result looks kind of nice for me. But I don't know what I was doing, I just want to eliminate the error and generated an plausible result.

**Comment by carlodef** [comment]
Hi @lionlai1989, thanks for reporting this issue. Could you please share the content of your input file `tmp.json` and the full error stack?
