### ISSUE TITLE
Urban areas issues

### ISSUE THREAD

**Issue by javierbecerra** [centreborelli/s2p#50]
Dear Carlo,
Finally we got to manage RPC's in a xml file from GBDX repository. We are quite amazed by the values (it is an area I know quite well and they are very similar to what I expected). However, we have run a test with a pair of images in an area mixed, half mountaineous, half urban and, even though the values in the hill area good, urban areas has not the detail we expected (in the image you can clearly see the streets but the buildings are quite fuzzy). 
There must be a parameter that change this in the config.py file, but I didn't find it. Could you tell what parameters are more related to this and how could I adjust them? 
Thanks in advance,
Javier

![Anotación 2020-04-23 113931](https://user-images.githubusercontent.com/21194894/80351185-2e244680-8872-11ea-92cd-3ade7287e997.png)
![Anotación 2020-04-23 113843](https://user-images.githubusercontent.com/21194894/80351189-2f557380-8872-11ea-8867-79de9ce38ba1.png)

**Comment by Sadrim-71** [comment]
Hi Javier
what was the source satellite imagery? (mainly the resolution).

**Comment by DieProgrammIDE** [comment]
Have the same problem with 30cm WorldView-3 Images

**Comment by oleg-alexandrov** [comment]
Urban areas can be a pain for stereo with satellite images. A building top may be just a few pixels wide, so buildings are tall, thin, and spiky, they cast long shadows, their glass reflects light in strange ways, and their surfaces can be in single color. Buildings also occlude each other, and they can look rather different in left vs right stereo image. Google Maps has nice 3D buildings, but I think their stereo is done based on airborne cameras which have higher resolution than satellites.

**Comment by gfacciol** [comment]
Maybe my message comes too late. I'll try to answer anyways. 
As @oleg-alexandrov points out urban areas are always a bit of a pain. 
However, at 30cm with relatively good angles it should give slightly better results than the one shown by @javierbecerra, see for instance https://gfacciol.github.io/multi-date-stereo/.

I think there might be an issue with the rectification. Concretely, when sift keypoint matching fails the rectification is done using only the RPC camera models. We can check that case by looking at the logs.
So, in the unlikely case you still have this experiment at hand you can upload here a tile from the urban area and we could have a look. 

In the meantime I will close this issue, but don't hesitate to reopen it.
